// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXRzFwZlvmw1eWo6YINmdFEHIAvxAYg-s',
    appId: '1:393165874421:web:d696a7397fd0b5892011bc',
    messagingSenderId: '393165874421',
    projectId: 'dinners-app-c2b68',
    authDomain: 'dinners-app-c2b68.firebaseapp.com',
    storageBucket: 'dinners-app-c2b68.firebasestorage.app',
    measurementId: 'G-8XLSFEG9NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuJdeJz_KHe9L2dJHdEikhRj1Qw8MpX0M',
    appId: '1:393165874421:android:63e5d6854b8145522011bc',
    messagingSenderId: '393165874421',
    projectId: 'dinners-app-c2b68',
    storageBucket: 'dinners-app-c2b68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxV70AsE2wMb6UsDxOC1GGfniNuReTkhE',
    appId: '1:393165874421:ios:bca15184dac9da292011bc',
    messagingSenderId: '393165874421',
    projectId: 'dinners-app-c2b68',
    storageBucket: 'dinners-app-c2b68.firebasestorage.app',
    androidClientId: '393165874421-1a5pn89fksoho3t0mg76b6th6j7hunp5.apps.googleusercontent.com',
    iosClientId: '393165874421-tp75cvt3jh11f52hdp915ag5jf6bdq1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinnersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxV70AsE2wMb6UsDxOC1GGfniNuReTkhE',
    appId: '1:393165874421:ios:bca15184dac9da292011bc',
    messagingSenderId: '393165874421',
    projectId: 'dinners-app-c2b68',
    storageBucket: 'dinners-app-c2b68.firebasestorage.app',
    androidClientId: '393165874421-1a5pn89fksoho3t0mg76b6th6j7hunp5.apps.googleusercontent.com',
    iosClientId: '393165874421-tp75cvt3jh11f52hdp915ag5jf6bdq1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinnersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXRzFwZlvmw1eWo6YINmdFEHIAvxAYg-s',
    appId: '1:393165874421:web:b0e99b8b1f7e86432011bc',
    messagingSenderId: '393165874421',
    projectId: 'dinners-app-c2b68',
    authDomain: 'dinners-app-c2b68.firebaseapp.com',
    storageBucket: 'dinners-app-c2b68.firebasestorage.app',
    measurementId: 'G-WYEFWW6WML',
  );
}
